services:
  db:
    image: postgres:15
    container_name: showu_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=showu
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: showu_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: showu_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    restart: always

  worker:
    build: .
    container_name: showu_worker
    command: celery -A app.utils.tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis