name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies and Build
        run: |
          if [ -d "ShowU" ]; then
            cd ShowU
          fi
          npm install
          npm run build
          if grep -q "next export" package.json; then
            npm run export
          else
            npx next export
          fi

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}