name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./showu-frontend
        run: npm install

      - name: Build Next.js
        working-directory: ./showu-frontend
        run: |
          export NEXT_TELEMETRY_DISABLED=1
          npx next build
        env:
          NEXT_DISABLE_ESLINT: 1
          NEXT_DISABLE_TYPECHECK: 1
          CI: false

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only hosting --project "8339b"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: showu-frontend