name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./showu-frontend
        run: npm install

      - name: Build Next.js (Force Build)
        working-directory: ./showu-frontend
        
        run: |
          export NEXT_TELEMETRY_DISABLED=1
          CI=false npx next build --no-lint

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v